name: Release

on:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      packages: write
    env:
      registry: 888469412714.dkr.ecr.us-east-2.amazonaws.com
      repository: 888469412714.dkr.ecr.us-east-2.amazonaws.com/benchmark-reports
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # checkout tags so version in Manifest is set properly

    - name: Configure Git user
      run: |
        git config user.email "releases@starburst.io"
        git config user.name "Starburst release automation"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      # locked to 2 commits after https://github.com/docker/login-action/releases/tag/v2.0.0
      uses: docker/login-action@d398f07826957cd0a18ea1b059cf1207835e60bc
      with:
        registry: ${{ env.registry }}
        username: ${{ secrets.ENG_AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.ENG_AWS_SECRET_ACCESS_KEY }}

    - name: Set release version
      run: |
        # if there's a SNAPSHOT suffix, remove it and commit changes
        DO_RELEASE=false
        if grep -q '^[0-9]\+-SNAPSHOT$' version; then
          sed -i 's/^\([0-9]\+\)-SNAPSHOT$/\1/' version
          VERSION=$(cat version)
          git diff
          git commit -a -m "Release: $VERSION"
          git tag -m "" "$VERSION"
          git log
          DO_RELEASE=true
        fi
        VERSION=$(cat version)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "DO_RELEASE=${DO_RELEASE}" >> $GITHUB_ENV

    - name: Make release
      run: |
        if [ "$DO_RELEASE" != "true" ]; then
          echo "Skipping the release step because not starting from a snapshot version"
          exit 0
        fi
        docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t "$repository:$VERSION" \
            --push \
            .
        docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t "$repository:latest" \
            --push \
            .

    - name: Set next development version
      run: |
        ((VERSION++))
        echo "$VERSION-SNAPSHOT" > version
        git diff
        git commit -a -m "Prepare for next development iteration"
        git log
        git push --tags origin main
